# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb23b9f9be8f0f8d80b51d2a8e43e7e2722359fd32708deb4894b4ba0e1b2de1216dd016e392876181647e9f73d4eea2341104217da57e2dd102d4521c3ae8e3

test:
  secret_key_base: 6ffe160dad08890f090638ab9b9c563cc83c7d551af4b901f771261a8484882b3440f4091b1aedec3ab175aba137678ca46c095124f9acd140da2530318b872b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
